### ISSUE TITLE
Multiple reports of crashes when joining servers

### ISSUE THREAD

**Issue by GamingGeek** [sk1erllc/Levelhead#14]
Multiple people have reported issues with levelhead in discord and the crash reports all seem to reference this line in levelhead.java: `https://github.com/sk1erllc/Levelhead/blob/873ba23f9152ba42a32ad4f93693676322800e8c/src/main/java/club/sk1er/mods/levelhead/Levelhead.java#L210`

I've added all the crash reports from discord into a gist for you:
https://gist.github.com/GamingGeek/c86b77beeb8a0e91055bbb12c70a800a

Thought I'd make an issue here since there's been a few people with the same issue

**Comment by OPAmqericaHPE** [comment]
I would be one of these people that are crashing, if anyone never saw #support in Sk1er's Discord

**Comment by Sk1er** [comment]
This should be fixed in Levelhead 6.2 Please let me know if you have further issues.

**Comment by OPAmqericaHPE** [comment]
I still have further issues regarding 6.2. I join the server for a second and then it crashes my game saying "Error whilst rendering entity" on my launcher. This only happens with the mod in. It's letting me on the server, but that's the issue I have with 6.2.
