### ISSUE TITLE
Incorrect colour coding using mediamod

### ISSUE THREAD

**Issue by TheAlmightyAlpaca** [Sk1erLLC/Levelhead#17]
Playing a song on Spotify using mediamod with '&' causes the following text's colours to be altered based on Minecraft colour codes. Foreign characters also do not display correctly. Mediamod's player displays correctly.

Eg. original text: Bülow: You & Jennifer
Result:
![image](https://user-images.githubusercontent.com/47854145/90311268-4363d480-df38-11ea-9e13-9e42d58909ee.png)

**Comment by Sk1er** [comment]
Not much we can do about the foreign characters, MC just doesn't have a good system for handling them.


As for the &, I have addressed this via an API update by substituting to and

**Comment by SystemlessDev** [comment]
Levelhead has removed support for Mediamod due to it not returning song info anymore.
