### ISSUE TITLE
Levels not showing properly

### ISSUE THREAD

**Issue by nxtdaydelivery** [Sk1erLLC/Levelhead#20]
hi.
I updated to the latest version earlier today and ever since the levels above people's heads have not been showing properly. I have tried removing my texture pack and seeing if it works but it does not. I cannot seem to find why it does this. 
When I change it off Normal mode(below), the Level part can become normal but the rest is still broken with a weird question mark, I believe this is related to the color prefixes Minecraft uses?

I am running MultiMC5, Forge Mod Loader version 11.15.1.2318 for Minecraft 1.8.9
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_281, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_281
If you need any more info, please ask.

Never had this issue before I updated today. Thanks.

Image of it with the prefix off Normal mode:
![image](https://user-images.githubusercontent.com/79922345/128541980-8fc9db34-2ef5-4a84-b4f7-cdaf86a0babc.png)
Images of it normally:
![image](https://user-images.githubusercontent.com/79922345/128542095-424b1ce5-99d6-4a81-979b-aea736d6d29b.png)
![image](https://user-images.githubusercontent.com/79922345/128542123-c447093d-5393-48d9-b1e4-810976843f65.png)

**Comment by GamingGeek** [comment]
This is a known issue. For now, you can delete the config (`level_head.cfg` in `.minecraft/config`) as a temporary fix.

Levelhead is currently being rewritten and this will likely resolve the issue.

**Comment by nxtdaydelivery** [comment]
Thanks! that seems to have fixed the problem.

**Comment by Sychic** [comment]
Resolved by 8bfc5b3
