### ISSUE TITLE
Custom backgrounds

### ISSUE THREAD

**Issue by solonovamax** [Sk1erLLC/Levelhead#21]
Option to change background color, including opacity.

Currently, it's impossible to have a transparent background. It would be very nice if that was possible.

I'll PR myself if I get time.

**Comment by Sychic** [comment]
You aren't meant to have a background color and the opacity is changed by [Patcher](https://github.com/Sk1erLLC/Patcher). There's currently a beta in our support & beta server which adds support for the things it changed for previous versions of levelhead.

**Comment by solonovamax** [comment]
I can't join the beta server because I'm banned in it
(very long story, ask asbyth if you want to know the reason, and you can dm me or something if you want to know more ig. I just don't want to bring stuff from inside the server to the outside, yk?)

Would I be able to build from source to get the current latest beta release?

**Comment by Sychic** [comment]
What's stopping you?

**Comment by solonovamax** [comment]
I'm just asking if the source contains the current beta releases, or if the beta releases are unpushed code?

**Comment by Sychic** [comment]
Why would the betas be unpushed? Seems rather counter intuitive from a version control standpoint.

**Comment by Sychic** [comment]
Anyways, just build from the 1.12.2 branch and you'll have the current beta (i think, maybe with some other stuff that isn't in a beta yet)
