### ISSUE TITLE
Personal level head broken when using patcher's "show own name tag"

### ISSUE THREAD

**Issue by solonovamax** [Sk1erLLC/Levelhead#22]
When displaying your own nametag with patcher, your levelhead does not display properly & overlaps with the nametag.
This happens exclusively in game modes where the health is displayed under the nametag.
![image](https://user-images.githubusercontent.com/46940694/148280742-48707f26-eb31-46a9-a05a-a676b07750a9.png)

Using the latest version of patcher, build from source.

**Comment by Sychic** [comment]
![image](https://user-images.githubusercontent.com/47618543/148282675-7b6a5c4b-e2f2-49b6-9030-19aad9cc8698.png)
Cannot reproduce.

**Comment by solonovamax** [comment]
Give me a bit to narrow down which specific mods produce this.
Perhaps it is caused by more than just patcher. Will comment if I can reproduce with a specific set of mods

**Comment by Sychic** [comment]
That is with every sk1er mod on (I think) the latest versions.

**Comment by solonovamax** [comment]
It may be a non-sk1er mod.

My full mods list is:

- PingTag Mod
- Sidebar Mod Revamp
- replaymod
- ArmorStatusHUD
- Autocorrect
- AutoFriend 
- AutoGG (customized version with personal changes)
- AutoReconnector
- Autotip
- AutoWho (mod I wrote that just types /who when it joins a game on hypixel. 0% chance it affects this.)
- BetterPvP
- BlockOverlay
- Bossbar Customizer
- BspkrsCore
- ChromaHUD
- Combat Info Mod
- Custom Crosshair Mod
- Damage Tint
- DiscordRP
- Essential Jars
- Hypixel Autocomplete
- Hytilities
- ItemPhysic Lite
- itemscroller
- Keystrokes
- Levelhead
- Presence Footsteps (Liteloader mod)
- Nick Hider
- Sk1er's Old Animations
- OptiFine
- Orange's Simple Mods
- ParticleMod
- Patcher (Latest version compiled from source)
- PerspectiveModv4
- Popup Events
- Powns Ghost Liquid Fix
- Powns PotionEffect HUD
- quickmaths (personal mod that just calculates the "quickmaths" challenges on hypixel)
- ReachDisplayMod
- RenderPlayerAPI
- Scrollable Tooltips
- Sk1er Bedwars Resource Display Mod
- StatusEffectHUD
- TimeChanger
- TNT Time
- ToggleChat
- Liteloader (Liteloader mod loader)

Everything should be latest version, or very near to that.

But, I'll save you the trouble of going through each mod & I'll do it myself.

**Comment by solonovamax** [comment]
I am reliably reproducing it with only patcher and levelhead:

![image](https://user-images.githubusercontent.com/46940694/148289023-17fd55b4-2222-4e7e-89b3-aeeb8510ec7a.png)

The "mods list" shows the following:
|Mod|Version|
|--|--|
|Minecraft Coder Pack|9.19
|Forge Mod Loader|8.0.99.99
|Minecraft Forge|11.15.2318
|Essential|1725
|LevelHead|8.0.0
|Patcher|1.7.0\*

\*(It actually shows `${version}`, but this is the latest version compiled from source)

Here are the config files for patcher, levelhead, and essentials, as well as the jars I used (you can check if for some reason they're not the latest version. Though, they should™ be.) (I'm unsure whether levelhead uses `LEVEL_HEAD.cfg`, `level_head.cfg`, or `levelhead.json`, so I've included all of them):

[LevelHead Nametag Bug.zip](https://github.com/Sk1erLLC/Levelhead/files/7817859/LevelHead.Nametag.Bug.zip)

Unzip the file in your `.minecraft` folder, and it will create `mods/`, `config/`, `essentials/config.toml`, and `options.txt`.

**Comment by solonovamax** [comment]
I forgot to upload this, but my log file can also be found here:

https://hst.sh/jidawofasi

**Comment by Sychic** [comment]
Try re-generating your patcher config by deleting it. Also try building patcher from source again

**Comment by solonovamax** [comment]
Did that.

Still reproducing.
![image](https://user-images.githubusercontent.com/46940694/148471299-9a8f42f8-b516-4f39-a9f7-5310759785c0.png)

**Comment by Sychic** [comment]
perhaps you compiled patcher wrong then

**Comment by solonovamax** [comment]
I did
```
./gradlew clean build
```
and copied the jar from `versions/1.8.9/build/libs`.
There was only 1 jar there.

**Comment by Sychic** [comment]
🤷 no clue then as it seems like it's just your version of patcher causing it at this point

**Comment by solonovamax** [comment]
Can you send me a version of patcher you compiled, so we can sanity check that?

**Comment by Sychic** [comment]
[This](https://cdn.discordapp.com/attachments/819543296765591552/927277486734209064/Patcher_1.8.0_-_rc_1_1.8.9.jar) Is the current beta version of patcher.

**Comment by solonovamax** [comment]
Thanks.

It seems that fixes it.

I'm not sure what I was doing wrong, in that case. I don't *believe* it was my build environment, but idk.

**Comment by asbyth** [comment]
> I forgot to upload this, but my log file can also be found here:
> 
> https://hst.sh/jidawofasi

```
[16:00:17] [Client thread/WARN] [mixin]: @ModifyConstant conflict. Skipping mixins.essential.json:client.gui.MixinGuiNewChat->@ModifyConstant::removeChatLimit(I)I with priority 1000, already redirected by patcher.mixins.json:features.GuiNewChatMixin_ExpandChatHistory->@ModifyConstant::patcher$expandChatHistory(I)I with priority 1000
```

You're building off master. This mixin does not exist in the branch where the betas actually are.

**Comment by solonovamax** [comment]
Ah, I see.
What branch is it in, then?
