### ISSUE TITLE
Crash on opening GUI

### ISSUE THREAD

**Issue by ojoeth** [Sk1erLLC/Levelhead#23]
Forge: 11.15.1.2318
MC: 1.8.9
Launcher: PolyMC 1.4.1 (Flatpak)
Only Levelhead is present in mods folder

Reproduce: type /levelhead, instead of opening GUI it crashes the game.

https://mclo.gs/bZsVpqC

**Comment by SystemlessDev** [comment]
You're on a outdated version of levelhead. This is already fixed.
https://sk1er.club/mods/level_head

**Comment by ojoeth** [comment]
Ah right, I was downloading from GitHub, didn't see the new relase. Thank you!
