### ISSUE TITLE
I can't use this MOD in China

### ISSUE THREAD

**Issue by mengzhu3261** [Sk1erLLC/Levelhead#27]
@Sk1er I can't use this MOD in China, and I can't access your website in China. If I use this MOD, I can't access the server. Can you fix this problem? pls

**Comment by mengzhu3261** [comment]
![Uploading image.png…

**Comment by mengzhu3261** [comment]
![image](https://github.com/Sk1erLLC/Levelhead/assets/147975362/c992b97d-671c-46ee-aa85-a313a723782a)

**Comment by mengzhu3261** [comment]
@Sk1er

**Comment by Sychic** [comment]
Hey, This isn't something we can fix as our network provider does not work in your country. It also appears that you are using an old version of the mod which may impact your experience.
